version: '3.3'

services:
  docker-github-runner:
      image: mataberat/github-runner:latest
      restart: always
      container_name: $runnerName
      environment:
        RUNNER_NAME: $runnerName
        REPO_URL: $repoURL
        RUNNER_TOKEN: $runnerToken
        RUNNER_WORKDIR: $runnerWorkDir
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - $runnerWorkDir:/tmp/github-runner
